### ISSUE TITLE
New ownership confirmation

### ISSUE THREAD

**Issue by adfoster-r7** [lemontree55/rasn1#39]
Hi there; I just wanted to confirm the context behind the repo/ownership transfer?
Are the accounts lemontree55 and sdaubert the same?

**Comment by lemontree55** [comment]
No, they are not.

**Comment by picatz** [comment]
👋 Also looking for some additional context behind the ownership transfer.

**Comment by sdaubert** [comment]
I transfered packetgen and rasn1 to @lemontree55  because i have no more time nor desire to work on them. Lemontree is a friend of mine, which created a brand new account to work on these projects.

**Comment by picatz** [comment]
I appreciate the additional context @sdaubert! Thank you for all the time and effort you put into those projects. You did an absolutely wonderful job, and I personally learned a lot from them.

@lemontree55 I look forward to your stewardship of these projects moving forward. Seems like you have some exciting ideas in mind for https://github.com/lemontree55/packetgen/pull/125 😄
